language: node_js

os:
  - osx

node_js:
 - "19.6.0"
 - "18.14.0"
 - "17.9.1"
 - "16.19.0"
 - "14.21.2"

install:
 - curl -sSL -k -o osx-net-core.pkg https://download.visualstudio.microsoft.com/download/pr/52bd43f7-88c9-420c-80c0-f19bae344293/a8d56f01fdb6f71adb5e22c3ddd1c3c6/dotnet-sdk-5.0.102-osx-x64.pkg
 - sudo installer -pkg osx-net-core.pkg -target /
 - export PATH=/usr/local/share/dotnet:$PATH
 - npm install -q

script:
 - dotnet --version
 - EDGE_USE_CORECLR=1 npm test
